---
# use shell rather than docker module
# to ensure osd disk prepare finishes before
# starting the next task
- name: prepare ceph containerized osd disk collocated
  shell: |
    docker run --net=host \
    --pid=host \
    --privileged=true \
    --name=ceph-osd-prepare-{{ ansible_hostname }}-{{ item | regex_replace('/dev/', '') }} \
    -v /etc/ceph:/etc/ceph:z \
    -v /var/lib/ceph/:/var/lib/ceph/:z \
    -v /dev:/dev \
    -v /etc/localtime:/etc/localtime:ro \
    -e DEBUG=verbose \
    -e CLUSTER={{ cluster }} \
    -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE \
    -e OSD_DEVICE={{ item }} \
    {{ docker_env_args }} \
    {{ ceph_osd_docker_prepare_env }} \
    {{ ceph_docker_registry }}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}
  with_items:
    - "{{ data_devices }}"
  when:
    - containerized_deployment
    - data_devices|length > 0

- name: manually prepare ceph "{{ osd_objectstore }}" non-containerized osd disk(s) with collocated osd data and journal
  command: "ceph-disk prepare {{ ceph_disk_cli_options }} {{ item }}"
  with_items:
    - "{{ data_devices }}"
  when:
    - not containerized_deployment
    - data_devices|length > 0