---
- name: set_fact lvm_volumes - build lvm_volumes dict based on choose_disk inputs if no input from the user
  set_fact:
    lvm_volumes:
      data: "{{ data_devices if data_devices|length==0 else block_devices }}"
  with_items:
    - "{{ data_devices }}"
  when:
    - lvm_volumes|length == 0


- name: "use ceph-volume to create {{ osd_objectstore }} osds"
  ceph_volume:
    cluster: "{{ cluster }}"
    objectstore: "{{ osd_objectstore }}"
    data: "{{ item.data }}"
    data_vg: "{{ item.data_vg|default(omit) }}"
    journal: "{{ item.journal|default(omit) }}"
    journal_vg: "{{ item.journal_vg|default(omit) }}"
    db: "{{ item.db|default(omit) }}"
    db_vg: "{{ item.db_vg|default(omit) }}"
    wal: "{{ item.wal|default(omit) }}"
    wal_vg: "{{ item.wal_vg|default(omit) }}"
    crush_device_class: "{{ item.crush_device_class|default(omit) }}"
    dmcrypt: "{{ dmcrypt|default(omit) }}"
  environment:
    CEPH_VOLUME_DEBUG: 1
  with_items: "{{ lvm_volumes }}"
