---
# use shell rather than docker module
# to ensure osd disk prepare finishes before
# starting the next task
- name: prepare ceph "{{ osd_objectstore }}" containerized osd disk(s) non-collocated
  shell: |
    docker run --net=host \
    --pid=host \
    --privileged=true \
    --name=ceph-osd-prepare-{{ ansible_hostname }}-{{ item.0 | regex_replace('/dev/', '') }} \
    -v /etc/ceph:/etc/ceph:z \
    -v /var/lib/ceph/:/var/lib/ceph/:z \
    -v /dev:/dev \
    -v /etc/localtime:/etc/localtime:ro \
    -e DEBUG=verbose \
    -e CLUSTER={{ cluster }} \
    -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE \
    -e OSD_DEVICE={{ item.0 }} \
    -e OSD_JOURNAL={{ item.1 }} \
    {{ docker_env_args }} \
    {{ ceph_osd_docker_prepare_env }} \
    {{ ceph_docker_registry }}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}
  with_together:
    - "{{ data_devices }}"
    - "{{ journal_devices }}"
  when:
    - containerized_deployment
    - osd_objectstore == 'filestore'
    - data_devices|length > 0
    - journal_devices|length > 0


- name: prepare ceph "{{ osd_objectstore }}" containerized osd disk(s) non-collocated with a dedicated device for db and wal
  shell: |
    docker run --net=host \
    --pid=host \
    --privileged=true \
    --name=ceph-osd-prepare-{{ ansible_hostname }}-{{ item.0 | regex_replace('/dev/', '') }} \
    -v /etc/ceph:/etc/ceph:z \
    -v /var/lib/ceph/:/var/lib/ceph/:z \
    -v /dev:/dev \
    -v /etc/localtime:/etc/localtime:ro \
    -e DEBUG=verbose \
    -e CLUSTER={{ cluster }} \
    -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE \
    -e OSD_DEVICE={{ item.0 }} \
    -e OSD_BLUESTORE_BLOCK_DB={{ item.1 }} \
    -e OSD_BLUESTORE_BLOCK_WAL={{ item.2 }} \
    {{ docker_env_args }} \
    {{ ceph_osd_docker_prepare_env }} \
    {{ ceph_docker_registry }}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}
  with_together:
    - "{{ block_devices }}"
    - "{{ db_devices }}"
    - "{{ wal_devices }}"
  when:
    - containerized_deployment
    - osd_objectstore == 'bluestore'
    - block_devices|length > 0
    - db_devices|length > 0
    - wal_devices|length > 0

- name: prepare ceph "{{ osd_objectstore }}" non-containerized osd disk(s) non-collocated
  command: "ceph-disk prepare {{ ceph_disk_cli_options }} {{ item.0 }} {{ item.1 }}"
  with_together:
    - "{{ data_devices }}"
    - "{{ journal_devices }}"
  changed_when: false
  when:
    - osd_objectstore == 'filestore'
    - not containerized_deployment
    - data_devices|length > 0
    - journal_devices|length > 0

- name: manually prepare ceph "{{ osd_objectstore }}" non-containerized osd disk(s) with a dedicated device for db and wal
  command: "ceph-disk prepare {{ ceph_disk_cli_options }} --block.db {{ item.0 }} --block.wal {{ item.1 }} {{ item.2 }}"
  with_together:
    - "{{ block_devices }}"
    - "{{ wal_devices }}"
    - "{{ db_devices }}"
  when:
    - osd_objectstore == 'bluestore'
    - not containerized_deployment
    - block_devices|length > 0
    - db_devices|length > 0
    - wal_devices|length > 0